name: nvbw_open_data
description: A selection of photos from the open data pool of NVBW GmbH.
homepage: https://www.nvbw.de/open-data

environment:
  sdk: ">=2.13.0 <3.0.0"

flutter:
  assets:
    - photos/